name: update

on:
  # schedule:
    - cron: "* * * * *""
  # run every 1 min


jobs:
  # run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      # TEST
      - name: Run my REMINDER script
        run: "LIFE IS BEAUTIFUL!!!"
 



     